### ISSUE TITLE
Proxy or ports not set up properly

### ISSUE THREAD

**Issue by mikkohei13** [DINA-Web/accounts-docker#10]
Using current documentation on readme-file does not set up the system properly: beta-accounts.dina-web.net cannot be reached.

Problem might be in setting up the proxy by docker-compose. Provide better documentation on how to do the setup (incl. getting certificates)

**Comment by mikkohei13** [comment]
This is probably due to missing certificates. Please include how to get/add certificates to the instructions.

**Comment by mskyttner** [comment]
@mikkohei13 here are instructions in the README.md: https://github.com/dina-web/proxy-docker/tree/self-signed-certs and the Makefile has a target there which may need a slight addition (of the beta-accounts.dina-web.net name). Details here: https://github.com/DINA-Web/proxy-docker/blob/self-signed-certs/Makefile#L9-L21

**Comment by mikkohei13** [comment]
Certificates were the issue preventing the module from running properly. Now we need to decide whether to instruct using self-signed vs. letsencrypt certificates for local builds, and then document how to do that  carefully here (as this is the reference implementation).

**Comment by mskyttner** [comment]
My vote is for self-signed certs, as it allows off-line mode without connecting external services such as the letsencrypt CA servce.

**Comment by mikkohei13** [comment]
Setting up self-signed certs resolved the issue. Clarifying the documentation on this would be preferable, especially since need to make browser to accept the certs to get the api to work. (Manually accepting an cert exception is not enough.)
