### ISSUE TITLE
Notification message - fix message and don't use internal server names

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/accounts-docker#13]
The notification message needs review of language and content, and it needs to use public and fully qualified domain names without the port specified for any links therein. 

Currently it looks like this:

`Your administrator has just requested that you update your dina account. Click on the link below to start this process.

http://sso:8080/auth/realms/dina/login-actions/execute-actions?key=<snap>

This link will expire within 1500 minutes.

If you are unaware that your admin has requested this, just ignore this message and nothing will be changed.

`

Perhaps keycloak uses the system hostname + domainname to construct the link? If so, this can be set in `docker-compose.yml` using `hostname` and `domainname`. I guess this is described somewhere in the keycloak documentation.

**Comment by mikkohei13** [comment]
This is described on Redmine issue https://support.dina-web.net/issues/1199 and is marked as resolved. It can be tested when latest version is deployed to Alpha.
