### ISSUE TITLE
Documentation need for how to configure the mailserver settings

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/accounts-docker#2]
The system has a dependency on an external mail server, such a component is currently not included in this setup. 

There is not yet any documentation describing where and how to configure this setting.

**Comment by mskyttner** [comment]
I think there is now a .yml file that could be used for this? The README.md does not describe how to use it. Should it be volume mounted into the Accounts API component? The README.md should also describe how to log in to the application with the default credentials provided in the .yml file, unless this should be configured using environment variables for the Accounts API component...

**Comment by mskyttner** [comment]
@mikkohei13 pls have a look at the README.md file - does it need more documentation to explain how to setup the email settings etc for the API?

**Comment by mskyttner** [comment]
@mikkohei13  - do you think the additions in 9ca92e5081a930aeba29ee76ed1e50f1b77f56b3 are understandable? If so, this can be closed.

**Comment by mikkohei13** [comment]
I think so. Making clarifications and reformatting for the readme here: https://github.com/mikkohei13/accounts-docker/blob/development/README.md
Will submit this as pull request, if I have understood the setup correctly.
