### ISSUE TITLE
Up-to-date package.json dependencies for accounts-ui

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/accounts-docker#8]
Update package.json dependencies for accounts-ui

It seems that package.json needs updating. It seems the build works without the     "broccoli-asset-rev": "^2.4.5" in the "package.json" file (somewhere I read that it is included in the ember-cli library) so maybe the versions and list of files there should be updated?  If so, perhaps this resource is helpful when updating the package.json file:

https://stackoverflow.com/questions/16073603/how-do-i-update-each-dependency-in-package-json-to-the-latest-version

**Comment by mikkohei13** [comment]
Is there need to do something for this? Current setup with "broccoli-asset-rev": "^2.4.5" in the "package.json" works.

There was change in Ember version in commit e6c6f7922186a31a7465724216d4eb35a59c3d77, so updating the package file would need thorough testing.

**Comment by mikkohei13** [comment]
Closing this issue as building the Ember UI has not been a problem anymore.
